### PR TITLE
Migrate to pydantic settings for FastAdmin configuration

### PR DESCRIPTION
**Pull request by bswck**
Since pydantic is a hard dependency, why not?

### Summary
Adds validation of configuration

### CODE REVIEW

**Comment by bswck** [comment]
I just noticed an intended removal of pydantic dependency in the issues and PRs which turns this PR into nonsense.
Feel free to either merge this PR or [correct the pyproject.toml file](https://github.com/vsdudakov/fastadmin/blob/3d473a097f04065e20649982252b47de3c1c16d6/pyproject.toml#L34).

**Comment by vsdudakov** [comment]
I had pydantic settings before, but decided to remove dependency from pydantic, cause from some cases we can  use fastadmin for django/flask and we don't want/need pydantic dependency here.

**Comment by vsdudakov** [comment]
Let me remove pydantic from toml

**Comment by vsdudakov** [comment]
Also it makes sense to use ADMIN prefix for settings cause could be some correlation with settings on projects which uses fastadmin

**Comment by vsdudakov** [comment]
Raised a ticket https://github.com/vsdudakov/fastadmin/issues/37

**Pull request closed without merging**
